name: Operator Test Workflow
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/operator.yaml'
      - 'operator/api/**'
      - 'operator/deploy/**'
      - 'operator/dist-template/**'
      - 'operator/Makefile'
      - 'operator/operator/**'
      - 'operator/pom.xml'
      - 'pom.xml'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/operator.yaml'
      - 'operator/api/**'
      - 'operator/deploy/**'
      - 'operator/dist-template/**'
      - 'operator/Makefile'
      - 'operator/operator/**'
      - 'operator/pom.xml'
      - 'pom.xml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  operator-build-test:
    name: Build and Test Operator
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jsenko' && !contains(github.event.*.labels.*.name, 'DO NOT MERGE')
    steps:

      - name: Configure env. variables
        run: |
          echo "IMAGE_REGISTRY=quay.io/jsenkorh" >> "$GITHUB_ENV"

      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: v1.33.1
          kubernetes version: v1.25.0
          github token: ${{ secrets.ACCESS_TOKEN }}
          start args: '--force'

      - name: Show Config
        run: |
          cd operator
          make config-show

      - name: Build and Test on Minikube
        run: |
          cd operator
          make BUILD_OPTS="--no-transfer-progress" build


  operator-publish:
    name: Publish Operator
    runs-on: ubuntu-latest
    needs: operator-build-test
    if: github.event_name == 'push'
    steps:

      - name: Configure env. variables
        run: |
          echo "IMAGE_REGISTRY=quay.io/jsenkorh" >> "$GITHUB_ENV"

      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Show Config
        run: |
          cd operator
          make config-show

      - name: Build
        run: |
          cd operator
          make BUILD_OPTS="--no-transfer-progress" SKIP_TESTS=true build

      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: |
          docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build and Publish Operator Image
        run: |
          cd operator
          make image-build image-push

      - name: Build and Publish Operator Bundle # TODO: Push to DockerHub Registry
        if: github.event_name == 'push'
        run: |
          cd operator
          make bundle          

      - name: Build and Publish Operator Catalog # TODO: Push to DockerHub Registry
        if: github.event_name == 'push'
        run: |
          cd operator
          make catalog          
  

  operator-update-install-file:
    name: Update Operator Install file
    runs-on: ubuntu-latest
    needs: operator-publish
    steps:

      - name: Configure env. variables
        run: |
          echo "IMAGE_REGISTRY=quay.io/jsenkorh" >> "$GITHUB_ENV"

      - name: Checkout ${{ github.ref_name }}
        run: |
          mkdir registry
          cd registry
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://jsenko:${{ secrets.ACCESS_TOKEN }}@github.com/jsenko/apicurio-registry.git"
          git fetch
          git checkout ${{ github.ref_name }}
          git branch --set-upstream-to=origin/${{ github.ref_name }}
          git pull

      - name: Show Config
        run: |
          cd operator
          make config-show

      - name: Build
        run: |
          cd registry/operator
          make BUILD_OPTS="--no-transfer-progress" SKIP_TESTS=true build

      - name: Update Install File
        run: |
          cd registry/operator
          make INSTALL_FILE=install/install.yaml dist-install-file

      - name: Commit and Push Install File
        run: |
          cd registry
          git add operator/install/install.yaml || true
          if ! git diff --cached --exit-code > /dev/null; then
            echo "Install file has changed!";
            git commit -m "ci: update operator install file"
            git push origin ${{ github.ref_name }}
          else
            echo "No changes :(";
          fi
