name: Static code analysis with Qodana
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
    branches:
      - main
      - qodana # TODO
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
    branches:
      - main
      - qodana # TODO

concurrency:
  # Only run once for the latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Qodana
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jsenko' && !contains(github.event.*.labels.*.name, 'DO NOT MERGE') # TODO
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout '${{ github.event.pull_request.head.sha }}'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --baseline,qodana.sarif.json
          # TODO push-fixes: pull-request
